url: "https://rethinkdbcloud.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "RethinkDBCloud" # the name of your site, e.g. ACME Corp.

business_name: "Mostly Typed"

# SEO (https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md)
# `tagline` is an unreleased feature and does not work, although it's mentioned in the seo plugin docs
# https://github.com/jekyll/jekyll-seo-tag/issues/379

description: "RethinkDBCloud provides a fast and reliable realtime database for Heroku. Conveniently scale your database up and down with a single command. Scale instantly and seamlessly, without loosing any data."
# google_site_verification: ""
twitter:
  card: summary_large_image

sass:
  style: compressed

autoprefixer:
  browsers:
    - last 2 versions

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-autoprefixer
