url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "RethinkHorizon" # the name of your site, e.g. ACME Corp.

business_name: "LamdaFunctional"
# TODO
mailchimp_form_action: ""

# SEO (https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md)
# `tagline` is an unreleased feature and does not work, although it's mentioned in the seo plugin docs
# https://github.com/jekyll/jekyll-seo-tag/issues/379

# Shorter descriptions
# "Reliable realtime RethinkDB databases for Heroku"
# "Fast and reliable realtime RethinkDB databases, with a secure admin dashboard, for your Heroku application."

# TODO title tbc, make sure it is up to date
# TODO Can we say 'fast'?
# TODO Can we say 'setup in seconds'?
description: "RethinkHorizon provides fast and reliable realtime RethinkDB databases for Heroku, with a secure admin dashboard. RethinkDB is the open source database for the realtime web, a document-orientated database with realtime updates for your Heroku application."
# TODO
google_site_verification: ""
twitter:
  card: summary_large_image

sass:
  style: compressed

autoprefixer:
  browsers:
    - last 2 versions

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-autoprefixer
